# RATIO 2019 - Benchmarking Workshop

In [1]:
import pandas as pd
import numpy as np
import pickle
import csv
from nltk.tokenize import sent_tokenize, word_tokenize

In [2]:
# GW split
with open("data/distinct_sets/within.pkl", "rb") as f:
    within_train_df = pickle.load(f)
    within_dev_df = pickle.load(f)
print(len(within_train_df))
print(len(within_dev_df))

42302
21601


In [3]:
# AH split
if False:
    with open("../argmining19-same-side-classification/data/distinct_sets/within/within_train_arg_pickle.pkl", "rb") as f:
        within_train_df = pickle.load(f)
    with open("../argmining19-same-side-classification/data/distinct_sets/within/within_dev_arg_pickle.pkl", "rb") as f:
        within_dev_df = pickle.load(f)
    tmp_all_train = set(within_train_df.argument1.tolist() + within_train_df.argument2.tolist())
    tmp_all_dev = set(within_dev_df.argument1.tolist() + within_dev_df.argument2.tolist())
    print(len(tmp_all_train))
    print(len(tmp_all_dev))
    print(len(tmp_all_train.intersection(tmp_all_dev)))

In [4]:
%env CUDA_DEVICE_ORDER=PCI_BUS_ID
%env CUDA_VISIBLE_DEVICES=5

env: CUDA_DEVICE_ORDER=PCI_BUS_ID
env: CUDA_VISIBLE_DEVICES=5


In [5]:
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score, f1_score
def report_training_results(y_test, y_pred):
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))  
    print()
    print('Accuracy: ', round(accuracy_score(y_test, y_pred), 2))  #
    print()

    print('Report:')
    print(classification_report(y_test, y_pred))  
    f1_dic = {}
    
    f1_dic['macro'] = round(f1_score(y_pred=y_pred, y_true=y_test, average='macro'), 2)
    f1_dic['micro'] = round(f1_score(y_pred=y_pred, y_true=y_test, average='micro'), 2)
    return f1_dic

In [6]:
if False:
    # Adding a tag for the topics in focus: "gay marriage" and "abortion"
    def add_tag(row):
        title = row['topic'].lower().strip()
        if title.find('abortion') > -1 :
            row['tag'] = 'abortion'
        elif title.find('gay marriage') > -1 :
            row['tag'] = 'gay marriage'
        else:
            row['tag'] = 'NA'
        return row

    within_train_df = within_train_df.apply(add_tag, axis=1)
    within_dev_df = within_dev_df.apply(add_tag, axis=1)
    # within_test_df = within_test_df.apply(add_tag, axis=1)
    
    with open("dev_tagged_data.pkl", "wb") as f:
        # pickle.dump(cross_train_df, f)
        # pickle.dump(cross_test_df, f)
        pickle.dump(within_train_df, f)
        pickle.dump(within_dev_df, f)

In [7]:
with open("dev_tagged_data.pkl", "rb") as f:
    within_train_df = pickle.load(f)
    within_dev_df = pickle.load(f)

In [8]:
print(within_train_df[["is_same_side", "tag"]].pivot_table(index="tag", columns='is_same_side', aggfunc=len))
print()
print(within_dev_df[["is_same_side", "tag"]].pivot_table(index="tag", columns='is_same_side', aggfunc=len))

is_same_side  False  True 
tag                       
abortion      11543  14593
gay marriage   5841  10325

is_same_side  False  True 
tag                       
abortion       8463   6241
gay marriage   3945   2952


In [9]:
def get_formatted_dataset(df):
    dataset = list(zip(df.argument1.tolist(), df.argument2.tolist(), df.is_same_side.tolist()))
    return dataset

In [10]:
X_train = get_formatted_dataset(within_train_df)
X_dev = get_formatted_dataset(within_dev_df)

In [11]:
# randomization experiments: 
# Exp 1: we shuffle the order of sentences in the dev set
# Exp 2: we shuffle the order of sentences in the training set

from nltk.tokenize import sent_tokenize
from random import shuffle

def shuffle_sentences(text):
    s = sent_tokenize(text)
    shuffle(s)
    return " ".join(s)

In [12]:
if False:
    X_dev_rnd = []
    for item in X_dev:
        X_dev_rnd.append((shuffle_sentences(item[0]), shuffle_sentences(item[1]), item[2]))
    X_dev = X_dev_rnd

    X_train_rnd = []
    for item in X_train:
        X_train_rnd.append((shuffle_sentences(item[0]), shuffle_sentences(item[1]), item[2]))
    X_train = X_train_rnd

# Within topic

In [13]:
from __future__ import absolute_import, division, print_function

import glob
import logging
import os
import random
import json

import numpy as np
import torch
from torch.utils.data import (DataLoader, RandomSampler, SequentialSampler, TensorDataset)
import random
from torch.utils.data.distributed import DistributedSampler
from tqdm.notebook import tqdm, trange

from tensorboardX import SummaryWriter

from transformers import (WEIGHTS_NAME, BertConfig, BertTokenizer,
                                  XLMConfig, XLMForSequenceClassification, XLMTokenizer, 
                                  XLNetConfig, XLNetForSequenceClassification, XLNetTokenizer,
                                  RobertaConfig, RobertaForSequenceClassification, RobertaTokenizer)

from transformers import AdamW, WarmupLinearSchedule

from utils import (convert_examples_to_features, output_modes, processors, BertForBinaryClassification, BertForSiameseClassification)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

In [14]:
args = {
    'data_dir': 'data/',
    'model_type':  'bert',
    'model_name': 'bert-base-uncased',
    'task_name': 'binary',
    'output_dir': 'outputs2/',
    'cache_dir': 'cache2/',
    'do_train': True,
    'do_eval': True,
    'fp16': False,
    'fp16_opt_level': 'O1',
    'max_seq_length': 512,
    'output_mode': 'classification',
    'train_batch_size': 8,
    'eval_batch_size': 8,

    'gradient_accumulation_steps': 1,
    'num_train_epochs': 3,
    'weight_decay': 0,
    'learning_rate': 5e-6,
    'adam_epsilon': 1e-9,
    'warmup_steps': 0,
    'max_grad_norm': 1.0,

    'logging_steps': 0,
    'evaluate_during_training': True,
    'save_steps': 1000,
    'eval_all_checkpoints': True,
    'overwrite_output_dir': False,
    'reprocess_input_data': True,
    'notes': 'SameSide argument classification task'
}
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [15]:
MODEL_CLASSES = {
    'bert': (BertConfig, BertForSiameseClassification, BertTokenizer),
    'xlnet': (XLNetConfig, XLNetForSequenceClassification, XLNetTokenizer),
    'xlm': (XLMConfig, XLMForSequenceClassification, XLMTokenizer),
    'roberta': (RobertaConfig, RobertaForSequenceClassification, RobertaTokenizer)
}

config_class, model_class, tokenizer_class = MODEL_CLASSES[args['model_type']]

In [16]:
config = config_class.from_pretrained(args['model_name'], num_labels=1, finetuning_task=args['task_name'])
tokenizer = tokenizer_class.from_pretrained(args['model_name'])

INFO:transformers.configuration_utils:loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /srv/home/gwiedemann/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": "binary",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.tokenization_utils:loading file https://s3.am

In [17]:
model = model_class.from_pretrained(args['model_name'], num_labels=1)

INFO:transformers.configuration_utils:loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /srv/home/gwiedemann/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file https://s3.am

In [18]:
model.to(device)

BertForSiameseClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementw

In [19]:
task = args['task_name']

processor = processors[task](X_train, X_dev)
label_list = processor.get_labels()
num_labels = 1

In [20]:
def load_and_cache_examples(task, tokenizer, evaluate=False):
    processor = processors[task](X_train, X_dev)
    output_mode = args['output_mode']
    
    mode = 'dev' if evaluate else 'train'
    cached_features_file = os.path.join(args['data_dir'], f"cached_{mode}_{args['model_name']}_{args['max_seq_length']}_{task}")
    
    if os.path.exists(cached_features_file) and not args['reprocess_input_data']:
        logger.info("Loading features from cached file %s", cached_features_file)
        features = torch.load(cached_features_file)
               
    else:
        logger.info("Creating features from dataset file at %s", args['data_dir'])
        label_list = processor.get_labels()
        examples = processor.get_dev_examples(args['data_dir']) if evaluate else processor.get_train_examples(args['data_dir'])
        
        features = convert_examples_to_features(examples, label_list, args['max_seq_length'], tokenizer, output_mode,
            cls_token_at_end=bool(args['model_type'] in ['xlnet']),            # xlnet has a cls token at the end
            cls_token=tokenizer.cls_token,
            sep_token=tokenizer.sep_token,
            cls_token_segment_id=2 if args['model_type'] in ['xlnet'] else 0,
            pad_on_left=bool(args['model_type'] in ['xlnet']),                 # pad on the left for xlnet
            pad_token_segment_id=4 if args['model_type'] in ['xlnet'] else 0)
        
        logger.info("Saving features into cached file %s", cached_features_file)
        torch.save(features, cached_features_file)
        
    all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long)
    all_input_mask = torch.tensor([f.input_mask for f in features], dtype=torch.long)
    all_segment_ids = torch.tensor([f.segment_ids for f in features], dtype=torch.long)
    # labels
    all_label_ids = torch.tensor([f.label_id for f in features], dtype=torch.float)

    dataset = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)
    return dataset

                                        
from pprint import pprint
                                        
def train(train_dataset, model, tokenizer):
    tb_writer = SummaryWriter()
    
    train_sampler = RandomSampler(train_dataset)
    train_dataloader = DataLoader(train_dataset, sampler=train_sampler, batch_size=args['train_batch_size'])
    
    t_total = len(train_dataloader) // args['gradient_accumulation_steps'] * args['num_train_epochs']
    
    no_decay = ['bias', 'LayerNorm.weight']
    optimizer_grouped_parameters = [
        {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': args['weight_decay']},
        {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
        ]
    optimizer = AdamW(optimizer_grouped_parameters, lr=args['learning_rate'], eps=args['adam_epsilon'])
    scheduler = WarmupLinearSchedule(optimizer, warmup_steps=args['warmup_steps'], t_total=t_total)
    
    if args['fp16']:
        try:
            from apex import amp
        except ImportError:
            raise ImportError("Please install apex from https://www.github.com/nvidia/apex to use fp16 training.")
        model, optimizer = amp.initialize(model, optimizer, opt_level=args['fp16_opt_level'])
        
    logger.info("***** Running training *****")
    logger.info("  Num examples = %d", len(train_dataset))
    logger.info("  Num Epochs = %d", args['num_train_epochs'])
    logger.info("  Total train batch size  = %d", args['train_batch_size'])
    logger.info("  Gradient Accumulation steps = %d", args['gradient_accumulation_steps'])
    logger.info("  Total optimization steps = %d", t_total)

    global_step = 0
    tr_loss, logging_loss = 0.0, 0.0
    model.zero_grad()
    train_iterator = trange(int(args['num_train_epochs']), desc="Epoch")
    
    for _ in train_iterator:
        epoch_iterator = tqdm(train_dataloader, desc="Iteration")
        for step, batch in enumerate(epoch_iterator):
            model.train()
            batch = tuple(t.to(device) for t in batch)
            inputs = {'input_ids':      batch[0],
                      'attention_mask': batch[1],
                      'token_type_ids': batch[2] if args['model_type'] in ['bert', 'xlnet'] else None,  # XLM don't use segment_ids
                      'labels':         batch[3]}
            outputs = model(**inputs)
            loss = outputs[0]  # model outputs are always tuple in pytorch-transformers (see doc)
            print("\r%f" % loss, end='')

            if args['gradient_accumulation_steps'] > 1:
                loss = loss / args['gradient_accumulation_steps']

            if args['fp16']:
                with amp.scale_loss(loss, optimizer) as scaled_loss:
                    scaled_loss.backward()
                torch.nn.utils.clip_grad_norm_(amp.master_params(optimizer), args['max_grad_norm'])
                
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), args['max_grad_norm'])

            tr_loss += loss.item()
            if (step + 1) % args['gradient_accumulation_steps'] == 0:

                optimizer.step()
                scheduler.step()  # Update learning rate schedule
                model.zero_grad()

                global_step += 1

                if args['logging_steps'] > 0 and global_step % args['logging_steps'] == 0:
                    # Log metrics
                    if args['evaluate_during_training']:  # Only evaluate when single GPU otherwise metrics may not average well
                        results, _ = evaluate(model, tokenizer)
                        for key, value in results.items():
                            tb_writer.add_scalar('eval_{}'.format(key), value, global_step)
                    tb_writer.add_scalar('lr', scheduler.get_lr()[0], global_step)
                    tb_writer.add_scalar('loss', (tr_loss - logging_loss)/args['logging_steps'], global_step)
                    logging_loss = tr_loss

                if args['save_steps'] > 0 and global_step % args['save_steps'] == 0:
                    # Save model checkpoint
                    output_dir = os.path.join(args['output_dir'], 'checkpoint-{}'.format(global_step))
                    if not os.path.exists(output_dir):
                        os.makedirs(output_dir)
                    model_to_save = model.module if hasattr(model, 'module') else model  # Take care of distributed/parallel training
                    model_to_save.save_pretrained(output_dir)
                    logger.info("Saving model checkpoint to %s", output_dir)


    return global_step, tr_loss / global_step

In [21]:
from sklearn.metrics import mean_squared_error, matthews_corrcoef, confusion_matrix, accuracy_score, f1_score
from scipy.stats import pearsonr

def get_mismatched(labels, preds):
    mismatched = labels != preds
    examples = processor.get_dev_examples(args['data_dir'])
    wrong = [i for (i, v) in zip(examples, mismatched) if v]
    
    return wrong

def get_eval_report(labels, preds):
    
    print(labels[:15])
    print(preds[:15])
    
    mcc = matthews_corrcoef(labels, preds)
    tn, fp, fn, tp = confusion_matrix(labels, preds).ravel()
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average='binary')
    f1_macro = f1_score(labels, preds, average='macro')
    f1_micro = f1_score(labels, preds, average='micro')
    return {
        "mcc": mcc,
        "tp": tp,
        "tn": tn,
        "fp": fp,
        "fn": fn,
        "acc" : acc,
        "f1" : f1,
        "f1_macro" : f1_macro,
        "f1_micro" : f1_micro
    }, get_mismatched(labels, preds)

def compute_metrics(task_name, preds, labels):
    assert len(preds) == len(labels)
    return get_eval_report(labels, preds)

def evaluate(model, tokenizer, prefix=""):
    # Loop to handle MNLI double evaluation (matched, mis-matched)
    eval_output_dir = args['output_dir']

    results = {}
    EVAL_TASK = args['task_name']

    eval_dataset = load_and_cache_examples(EVAL_TASK, tokenizer, evaluate=True)
    if not os.path.exists(eval_output_dir):
        os.makedirs(eval_output_dir)


    eval_sampler = SequentialSampler(eval_dataset)
    eval_dataloader = DataLoader(eval_dataset, sampler=eval_sampler, batch_size=args['eval_batch_size'])

    # Eval!
    logger.info("***** Running evaluation {} *****".format(prefix))
    logger.info("  Num examples = %d", len(eval_dataset))
    logger.info("  Batch size = %d", args['eval_batch_size'])
    eval_loss = 0.0
    nb_eval_steps = 0
    preds = None
    out_label_ids = None
    
    sigmoid_squash = torch.nn.Sigmoid()
    cosine_squash = lambda x : (x + 1.) / 2.
    
    for batch in tqdm(eval_dataloader, desc="Evaluating"):
        model.eval()
        batch = tuple(t.to(device) for t in batch)

        with torch.no_grad():
            inputs = {'input_ids':      batch[0],
                      'attention_mask': batch[1],
                      'token_type_ids': batch[2] if args['model_type'] in ['bert', 'xlnet'] else None,  # XLM don't use segment_ids
                      'labels':         batch[3]}
            outputs = model(**inputs)
            tmp_eval_loss, logits = outputs[:2]
            
            # sigmoid output
            # logits = sigmoid_squash(logits)
            # cosine output
            logits = cosine_squash(logits)

            eval_loss += tmp_eval_loss.mean().item()
        nb_eval_steps += 1
        
        if preds is None:
            preds = logits.detach().cpu().numpy()
            out_label_ids = inputs['labels'].detach().cpu().numpy()
        else:
            preds = np.append(preds, logits.detach().cpu().numpy())
            out_label_ids = np.append(out_label_ids, inputs['labels'].detach().cpu().numpy(), axis=0)

    eval_loss = eval_loss / nb_eval_steps
    if args['output_mode'] == "classification":
        # preds = np.argmax(preds, axis=1)
        preds = np.round(preds).astype(int)
    elif args['output_mode'] == "regression":
        preds = np.squeeze(preds)
    # print(preds)
    result, wrong = compute_metrics(EVAL_TASK, preds, out_label_ids)
    results.update(result)

    output_eval_file = os.path.join(eval_output_dir, "eval_results.txt")
    with open(output_eval_file, "w") as writer:
        logger.info("***** Eval results {} *****".format(prefix))
        for key in sorted(result.keys()):
            logger.info("  %s = %s", key, str(result[key]))
            writer.write("%s = %s\n" % (key, str(result[key])))

    return results, wrong

In [22]:
from tensorboardX import SummaryWriter

In [23]:
if args['do_train']:
    train_dataset = load_and_cache_examples(task, tokenizer)
    global_step, tr_loss = train(train_dataset, model, tokenizer)
    logger.info(" global_step = %s, average loss = %s", global_step, tr_loss)

INFO:__main__:Creating features from dataset file at data/
100%|██████████| 42302/42302 [00:17<00:00, 2411.98it/s]
INFO:__main__:Saving features into cached file data/cached_train_bert-base-uncased_512_binary
INFO:__main__:***** Running training *****
INFO:__main__:  Num examples = 42302
INFO:__main__:  Num Epochs = 3
INFO:__main__:  Total train batch size  = 8
INFO:__main__:  Gradient Accumulation steps = 1
INFO:__main__:  Total optimization steps = 15864


0.051486

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-1000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-1000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-1000


0.075657

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-2000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-2000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-2000


0.067545

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-3000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-3000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-3000


0.361088

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-4000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-4000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-4000


0.034844

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-5000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-5000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-5000


0.226072


0.074345

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-6000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-6000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-6000


0.276036

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-7000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-7000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-7000


0.076813

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-8000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-8000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-8000


0.088360

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-9000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-9000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-9000


0.287372

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-10000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-10000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-10000


0.015548


0.185572

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-11000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-11000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-11000


0.073236

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-12000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-12000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-12000


0.169724

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-13000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-13000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-13000


0.037500

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-14000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-14000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-14000


0.076347

INFO:transformers.configuration_utils:Configuration saved in outputs2/checkpoint-15000/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/checkpoint-15000/pytorch_model.bin
INFO:__main__:Saving model checkpoint to outputs2/checkpoint-15000


0.067400

INFO:__main__: global_step = 15864, average loss = 0.13139258421149924


In [24]:
if args['do_train']:
    if not os.path.exists(args['output_dir']):
            os.makedirs(args['output_dir'])
    logger.info("Saving model checkpoint to %s", args['output_dir'])
    
    model_to_save = model.module if hasattr(model, 'module') else model  # Take care of distributed/parallel training
    model_to_save.save_pretrained(args['output_dir'])
    tokenizer.save_pretrained(args['output_dir'])
    torch.save(args, os.path.join(args['output_dir'], 'training_args.bin'))

INFO:__main__:Saving model checkpoint to outputs2/
INFO:transformers.configuration_utils:Configuration saved in outputs2/config.json
INFO:transformers.modeling_utils:Model weights saved in outputs2/pytorch_model.bin


In [25]:
## Evaluation

In [26]:
if args['do_eval']:
    results = {}
    checkpoints = [args['output_dir']]
    if args['eval_all_checkpoints']:
        checkpoints = list(os.path.dirname(c) for c in sorted(glob.glob(args['output_dir'] + '/**/' + WEIGHTS_NAME, recursive=True)))
        logging.getLogger("pytorch_transformers.modeling_utils").setLevel(logging.WARN)  # Reduce logging
    logger.info("Evaluate the following checkpoints: %s", checkpoints)
    for checkpoint in checkpoints:
        global_step = checkpoint.split('-')[-1] if len(checkpoints) > 1 else ""
        model = model_class.from_pretrained(checkpoint)
        model.to(device)
        result, wrong_preds = evaluate(model, tokenizer, prefix=global_step)
        result = dict((k + '_{}'.format(global_step), v) for k, v in result.items())
        results.update(result)

INFO:__main__:Evaluate the following checkpoints: ['outputs2/checkpoint-1000', 'outputs2/checkpoint-10000', 'outputs2/checkpoint-11000', 'outputs2/checkpoint-12000', 'outputs2/checkpoint-13000', 'outputs2/checkpoint-14000', 'outputs2/checkpoint-15000', 'outputs2/checkpoint-2000', 'outputs2/checkpoint-3000', 'outputs2/checkpoint-4000', 'outputs2/checkpoint-5000', 'outputs2/checkpoint-6000', 'outputs2/checkpoint-7000', 'outputs2/checkpoint-8000', 'outputs2/checkpoint-9000', 'outputs2']
INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-1000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions


[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:__main__:***** Eval results 1000 *****
INFO:__main__:  acc = 0.42710985602518403
INFO:__main__:  f1 = 0.5964191370707367
INFO:__main__:  f1_macro = 0.3047491649944161
INFO:__main__:  f1_micro = 0.42710985602518403
INFO:__main__:  fn = 49
INFO:__main__:  fp = 12326
INFO:__main__:  mcc = 0.008141934335312557
INFO:__main__:  tn = 82
INFO:__main__:  tp = 9144
INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-10000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab

INFO:__main__:***** Eval results 10000 *****
INFO:__main__:  acc = 0.4369242164714597
INFO:__main__:  f1 = 0.5840145011799309
INFO:__main__:  f1_macro = 0.3564633130407282
INFO:__main__:  f1_micro = 0.4369242164714597
INFO:__main__:  fn = 655
INFO:__main__:  fp = 11508
INFO:__main__:  mcc = 0.002456181453166064
INFO:__main__:  tn = 900
INFO:__main__:  tp = 8538



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-11000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/checkpoint-11000/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:26<00:00, 807.21it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binar

INFO:__main__:***** Eval results 11000 *****
INFO:__main__:  acc = 0.43123003564649787
INFO:__main__:  f1 = 0.595615825159634
INFO:__main__:  f1_macro = 0.31863474565313993
INFO:__main__:  f1_micro = 0.43123003564649787
INFO:__main__:  fn = 145
INFO:__main__:  fp = 12141
INFO:__main__:  mcc = 0.020768439182785654
INFO:__main__:  tn = 267
INFO:__main__:  tp = 9048



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-12000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/checkpoint-12000/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:27<00:00, 796.40it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binar

INFO:__main__:***** Eval results 12000 *****
INFO:__main__:  acc = 0.43173927133003104
INFO:__main__:  f1 = 0.595778311983403
INFO:__main__:  f1_macro = 0.3197045046477202
INFO:__main__:  f1_micro = 0.43173927133003104
INFO:__main__:  fn = 147
INFO:__main__:  fp = 12128
INFO:__main__:  mcc = 0.023356265707307283
INFO:__main__:  tn = 280
INFO:__main__:  tp = 9046
INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-13000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_voc


[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:26<00:00, 800.56it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary
INFO:__main__:***** Running evaluation 13000 *****
INFO:__main__:  Num examples = 21601
INFO:__main__:  Batch size = 8



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:__main__:***** Eval results 13000 *****
INFO:__main__:  acc = 0.434100273135503
INFO:__main__:  f1 = 0.5917440384743838
INFO:__main__:  f1_macro = 0.3349368759491074
INFO:__main__:  f1_micro = 0.434100273135503
INFO:__main__:  fn = 334
INFO:__main__:  fp = 11890
INFO:__main__:  mcc = 0.013755649532819344
INFO:__main__:  tn = 518
INFO:__main__:  tp = 8859
INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-14000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_

INFO:__main__:***** Eval results 14000 *****
INFO:__main__:  acc = 0.43261886023795193
INFO:__main__:  f1 = 0.5941453076362673
INFO:__main__:  f1_macro = 0.32583303523923485
INFO:__main__:  f1_micro = 0.43261886023795193
INFO:__main__:  fn = 222
INFO:__main__:  fp = 12034
INFO:__main__:  mcc = 0.018090137613471058
INFO:__main__:  tn = 374
INFO:__main__:  tp = 8971
INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-15000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_v


[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:44<00:00, 481.88it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary
INFO:__main__:***** Running evaluation 15000 *****
INFO:__main__:  Num examples = 21601
INFO:__main__:  Batch size = 8


INFO:__main__:***** Eval results 15000 *****
INFO:__main__:  acc = 0.43303550761538817
INFO:__main__:  f1 = 0.593972748068826
INFO:__main__:  f1_macro = 0.32735680121441146
INFO:__main__:  f1_micro = 0.43303550761538817
INFO:__main__:  fn = 235
INFO:__main__:  fp = 12012
INFO:__main__:  mcc = 0.01864978135707262
INFO:__main__:  tn = 396
INFO:__main__:  tp = 8958



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-2000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/checkpoint-2000/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:27<00:00, 778.87it/s] 
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary

INFO:__main__:***** Eval results 2000 *****
INFO:__main__:  acc = 0.4283597981574927
INFO:__main__:  f1 = 0.5963914493037851
INFO:__main__:  f1_macro = 0.30850663835747627
INFO:__main__:  f1_micro = 0.4283597981574927
INFO:__main__:  fn = 70
INFO:__main__:  fp = 12278
INFO:__main__:  mcc = 0.014777859545060987
INFO:__main__:  tn = 130
INFO:__main__:  tp = 9123
INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-3000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_


[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:27<00:00, 773.95it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary
INFO:__main__:***** Running evaluation 3000 *****
INFO:__main__:  Num examples = 21601
INFO:__main__:  Batch size = 8


INFO:__main__:***** Eval results 3000 *****
INFO:__main__:  acc = 0.42710985602518403
INFO:__main__:  f1 = 0.5965770171149144
INFO:__main__:  f1_macro = 0.30435540406316486
INFO:__main__:  f1_micro = 0.42710985602518403
INFO:__main__:  fn = 43
INFO:__main__:  fp = 12332
INFO:__main__:  mcc = 0.009669852314217698
INFO:__main__:  tn = 76
INFO:__main__:  tp = 9150



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-4000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/checkpoint-4000/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:28<00:00, 757.35it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary


INFO:__main__:***** Eval results 4000 *****
INFO:__main__:  acc = 0.4293319753715106
INFO:__main__:  f1 = 0.5956902489422415
INFO:__main__:  f1_macro = 0.3130264349407188
INFO:__main__:  f1_micro = 0.4293319753715106
INFO:__main__:  fn = 112
INFO:__main__:  fp = 12215
INFO:__main__:  mcc = 0.01412790423961469
INFO:__main__:  tn = 193
INFO:__main__:  tp = 9081



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-5000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/checkpoint-5000/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:28<00:00, 752.04it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary


INFO:__main__:***** Eval results 5000 *****
INFO:__main__:  acc = 0.43016527012638306
INFO:__main__:  f1 = 0.595138637634444
INFO:__main__:  f1_macro = 0.31671143929538437
INFO:__main__:  f1_micro = 0.43016527012638306
INFO:__main__:  fn = 146
INFO:__main__:  fp = 12163
INFO:__main__:  mcc = 0.01432918757064571
INFO:__main__:  tn = 245
INFO:__main__:  tp = 9047



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-6000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/checkpoint-6000/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:28<00:00, 758.41it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary


INFO:__main__:***** Eval results 6000 *****
INFO:__main__:  acc = 0.4300263876672376
INFO:__main__:  f1 = 0.5939313984168866
INFO:__main__:  f1_macro = 0.319089593013753
INFO:__main__:  f1_micro = 0.4300263876672376
INFO:__main__:  fn = 189
INFO:__main__:  fp = 12123
INFO:__main__:  mcc = 0.008133473789221595
INFO:__main__:  tn = 285
INFO:__main__:  tp = 9004



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-7000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/checkpoint-7000/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:28<00:00, 757.17it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary


INFO:__main__:***** Eval results 7000 *****
INFO:__main__:  acc = 0.42845238646358963
INFO:__main__:  f1 = 0.5956108745496232
INFO:__main__:  f1_macro = 0.31066844232531665
INFO:__main__:  f1_micro = 0.42845238646358963
INFO:__main__:  fn = 101
INFO:__main__:  fp = 12245
INFO:__main__:  mcc = 0.009675259507025788
INFO:__main__:  tn = 163
INFO:__main__:  tp = 9092



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-8000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/checkpoint-8000/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:28<00:00, 756.12it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary


INFO:__main__:***** Eval results 8000 *****
INFO:__main__:  acc = 0.42937826952455904
INFO:__main__:  f1 = 0.5966623036649215
INFO:__main__:  f1_macro = 0.3108291742972606
INFO:__main__:  f1_micro = 0.42937826952455904
INFO:__main__:  fn = 76
INFO:__main__:  fp = 12250
INFO:__main__:  mcc = 0.021334036240444307
INFO:__main__:  tn = 158
INFO:__main__:  tp = 9117
INFO:transformers.configuration_utils:loading configuration file outputs2/checkpoint-9000/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab


[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:28<00:00, 753.85it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary
INFO:__main__:***** Running evaluation 9000 *****
INFO:__main__:  Num examples = 21601
INFO:__main__:  Batch size = 8


INFO:__main__:***** Eval results 9000 *****
INFO:__main__:  acc = 0.43058191750381924
INFO:__main__:  f1 = 0.5953148647759425
INFO:__main__:  f1_macro = 0.31748878779084444
INFO:__main__:  f1_micro = 0.43058191750381924
INFO:__main__:  fn = 146
INFO:__main__:  fp = 12154
INFO:__main__:  mcc = 0.016830260252931748
INFO:__main__:  tn = 254
INFO:__main__:  tp = 9047



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


INFO:transformers.configuration_utils:loading configuration file outputs2/config.json
INFO:transformers.configuration_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

INFO:transformers.modeling_utils:loading weights file outputs2/pytorch_model.bin
INFO:__main__:Creating features from dataset file at data/
100%|██████████| 21601/21601 [00:28<00:00, 757.97it/s]
INFO:__main__:Saving features into cached file data/cached_dev_bert-base-uncased_512_binary
INFO:__main__:***** Running eval

INFO:__main__:***** Eval results outputs2 *****
INFO:__main__:  acc = 0.43428544974769684
INFO:__main__:  f1 = 0.5922589255922589
INFO:__main__:  f1_macro = 0.3343700915748477
INFO:__main__:  f1_micro = 0.43428544974769684
INFO:__main__:  fn = 318
INFO:__main__:  fp = 11902
INFO:__main__:  mcc = 0.015974131192990473
INFO:__main__:  tn = 506
INFO:__main__:  tp = 8875



[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
