In [1]:
import torch
import pickle

In [142]:
with open("pooled_output.pkl", "rb") as f:
    pooled_output = pickle.load(f)
    token_type_ids = pickle.load(f)
    input_ids = pickle.load(f)
    labels = pickle.load(f)

In [36]:
print(list(pooled_output[0].size())) # last hidden layer
print(list(pooled_output[1].size())) # pooled output
# bs sl nd

[8, 512, 768]
[8, 768]


In [152]:
print(labels)
torch.where(labels.detach().cpu() > 0, torch.ones(8), -torch.ones(8))

tensor([0., 0., 0., 1., 0., 0., 0., 0.], device='cuda:0')


tensor([-1., -1., -1.,  1., -1., -1., -1., -1.])

In [157]:
pooled_output[0][0].mean(axis=1)

tensor([-0.0132, -0.0118, -0.0147, -0.0147, -0.0112, -0.0162, -0.0157, -0.0132,
        -0.0105, -0.0114, -0.0108, -0.0134, -0.0114, -0.0127, -0.0106, -0.0138,
        -0.0098, -0.0114, -0.0095, -0.0124, -0.0106, -0.0095, -0.0102, -0.0096,
        -0.0097, -0.0130, -0.0162, -0.0163, -0.0124, -0.0125, -0.0150, -0.0139,
        -0.0142, -0.0169, -0.0115, -0.0138, -0.0088, -0.0110, -0.0090, -0.0105,
        -0.0093, -0.0114, -0.0132, -0.0104, -0.0127, -0.0103, -0.0114, -0.0115,
        -0.0132, -0.0132, -0.0159, -0.0176, -0.0127, -0.0135, -0.0152, -0.0107,
        -0.0080, -0.0094, -0.0148, -0.0124, -0.0078, -0.0118, -0.0143, -0.0108,
        -0.0097, -0.0145, -0.0104, -0.0147, -0.0145, -0.0140, -0.0133, -0.0119,
        -0.0088, -0.0145, -0.0097, -0.0123, -0.0106, -0.0106, -0.0129, -0.0129,
        -0.0132, -0.0122, -0.0100, -0.0103, -0.0111, -0.0127, -0.0121, -0.0129,
        -0.0116, -0.0120, -0.0131, -0.0152, -0.0150, -0.0110, -0.0117, -0.0113,
        -0.0132, -0.0111, -0.0123, -0.01

In [59]:
print(token_type_ids.size())
print(input_ids.size())

torch.Size([8, 512])
torch.Size([8, 512])


In [41]:
token_type_ids[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [47]:
input_ids[0]

tensor([  101,  5035,  2080,  5443,  1012, 13433,  3630,  1025,  2591,  3314,
         1010,  5637,  3510,  7929,  2026, 12191, 14180,  2039,  1012,  2021,
         2054,  2003,  3308,  2007,  5637,  3510,  1029,  2065,  2017,  2228,
         2009,  1005,  1055,  3308,  2507,  2033,  4436,  1012,  1045,  2106,
         2360,  1045,  2342,  2009,  2000,  3926,  1037,  3259,  1012,  1045,
         2342,  2500, 10740,  1010,  1045,  2123,  1005,  1056,  2729,  2065,
         6343, 10217,  1012,  2021,  2065,  2017,  2695, 16215,  2595,  1012,
         2067,  2000,  1996,  2391,  2003,  2045,  2003,  2498,  3308,  2007,
         5637,  3510,  1010,  2043,  2017,  2131,  2496,  2000,  2070,  2028,
         2017,  2293,  2068,  1010,  1006, 11504,  1007,  1010,  1998,  1996,
         5637,  2015,  2041,  1999,  1996,  2088,  2087,  3497,  2293,  2037,
         4256,  2205,   999,   102,  5035,  2080,  5443,  1012, 13433,  3630,
         1025,  2591,  3314,  1010,  5637,  3510,  1045,  2572, 

In [48]:
input_ids[0][token_type_ids[0].bool()]

tensor([ 5035,  2080,  5443,  1012, 13433,  3630,  1025,  2591,  3314,  1010,
         5637,  3510,  1045,  2572,  2025,  2114,  5637, 22231, 21285,  5454,
         2040,  2027,  2215,  2000,  5914,  2045,  2003,  2498,  3308,  2007,
         2108,  5637,  1010,  4654, 25154,  2009,  2000,  1996,  2088,  2049,
         2025,  1037,  2919,  2518,  1012,  3510,  2138,  2111,  1010,  2021,
         1045,  2342, 10848, 10740,  2000,  3926,  1012,   102],
       device='cuda:0')

In [115]:
tmp = input_ids[0][~token_type_ids[0].bool()]
tmp

tensor([  101,  5035,  2080,  5443,  1012, 13433,  3630,  1025,  2591,  3314,
         1010,  5637,  3510,  7929,  2026, 12191, 14180,  2039,  1012,  2021,
         2054,  2003,  3308,  2007,  5637,  3510,  1029,  2065,  2017,  2228,
         2009,  1005,  1055,  3308,  2507,  2033,  4436,  1012,  1045,  2106,
         2360,  1045,  2342,  2009,  2000,  3926,  1037,  3259,  1012,  1045,
         2342,  2500, 10740,  1010,  1045,  2123,  1005,  1056,  2729,  2065,
         6343, 10217,  1012,  2021,  2065,  2017,  2695, 16215,  2595,  1012,
         2067,  2000,  1996,  2391,  2003,  2045,  2003,  2498,  3308,  2007,
         5637,  3510,  1010,  2043,  2017,  2131,  2496,  2000,  2070,  2028,
         2017,  2293,  2068,  1010,  1006, 11504,  1007,  1010,  1998,  1996,
         5637,  2015,  2041,  1999,  1996,  2088,  2087,  3497,  2293,  2037,
         4256,  2205,   999,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0, 

In [116]:
tmp1 = input_ids.bool() * token_type_ids.bool()
tmp2 = input_ids.bool() * ~token_type_ids.bool()
tmp2[0]

tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, 

In [72]:
tmp1.size()

torch.Size([8, 512])

In [87]:
pooled_output[0][0][tmp[0]].size()

torch.Size([58, 768])

In [167]:
# classifier = torch.nn.Sequential(
#             torch.nn.Linear(nd, nd),
#             torch.nn.Tanh()
#         )
classifier = torch.nn.Sequential(
            torch.nn.Linear(nd, nd),
            torch.nn.Sigmoid()
        )

In [199]:
last_hidden_state = pooled_output[0]
selection_left = input_ids.bool() * ~token_type_ids.bool()
selection_left[:,0] = False # do not use CLS token
selection_right = input_ids.bool() * token_type_ids.bool()

dims = list(last_hidden_state.size())
bs = dims[0]
nd = dims[2] 
mean_left = torch.zeros((bs, nd))
mean_right = torch.zeros((bs, nd))
for i in range(bs):
    mean_left[i] = last_hidden_state[i][selection_left[i]].mean(axis=0)
    mean_right[i] = last_hidden_state[i][selection_right[i]].mean(axis=0)
emb_left = classifier(mean_left)
emb_right = classifier(mean_right)

In [191]:
loss_fct = torch.nn.CosineEmbeddingLoss()

In [192]:
cosine_labels = torch.where(labels.detach().cpu() > 0, torch.ones(bs), -torch.ones(bs))
loss_fct(emb_left, emb_right, cosine_labels)

tensor(0.8740, grad_fn=<MeanBackward0>)

In [204]:
qn_left = emb_left.norm(p=2, dim=1, keepdim=True)
emb_left_norm = emb_left.div(qn_left.expand_as(emb_left))

qn_right = emb_right.norm(p=2, dim=1, keepdim=True)
emb_right_norm = emb_right.div(qn_right.expand_as(emb_right))

torch.matmul(emb_left_norm, emb_right_norm.t())

tensor([[0.9991, 0.9988, 0.9985, 0.9984, 0.9989, 0.9990, 0.9986, 0.9988],
        [0.9987, 0.9993, 0.9984, 0.9986, 0.9990, 0.9988, 0.9985, 0.9983],
        [0.9981, 0.9979, 0.9976, 0.9973, 0.9977, 0.9980, 0.9978, 0.9986],
        [0.9987, 0.9988, 0.9986, 0.9991, 0.9988, 0.9989, 0.9984, 0.9984],
        [0.9985, 0.9985, 0.9988, 0.9985, 0.9989, 0.9987, 0.9981, 0.9978],
        [0.9988, 0.9989, 0.9982, 0.9982, 0.9986, 0.9990, 0.9984, 0.9989],
        [0.9991, 0.9991, 0.9986, 0.9989, 0.9990, 0.9992, 0.9989, 0.9986],
        [0.9990, 0.9989, 0.9985, 0.9988, 0.9989, 0.9992, 0.9987, 0.9986]],
       grad_fn=<MmBackward>)

In [194]:
emb_left_norm

tensor([[0.0389, 0.0347, 0.0327,  ..., 0.0357, 0.0311, 0.0363],
        [0.0371, 0.0349, 0.0353,  ..., 0.0384, 0.0304, 0.0390],
        [0.0357, 0.0340, 0.0324,  ..., 0.0367, 0.0342, 0.0328],
        ...,
        [0.0378, 0.0343, 0.0320,  ..., 0.0376, 0.0331, 0.0369],
        [0.0361, 0.0339, 0.0308,  ..., 0.0355, 0.0309, 0.0378],
        [0.0364, 0.0338, 0.0328,  ..., 0.0375, 0.0309, 0.0385]],
       grad_fn=<DivBackward0>)

In [195]:
qn_left

tensor([[13.8917],
        [13.8998],
        [13.8913],
        [13.8980],
        [13.8797],
        [13.9052],
        [13.8956],
        [13.8807]], grad_fn=<NormBackward1>)

In [196]:
emb_left_norm.sum(axis=1)

tensor([27.6228, 27.6019, 27.5929, 27.6011, 27.6011, 27.6188, 27.6106, 27.6132],
       grad_fn=<SumBackward1>)

In [218]:
from sklearn.metrics import f1_score

true = [1,1,1,1,1,1,0,0,0,0]
pred = [1,1,1,1,1,1,1,1,1,0]

print(f1_score(true, pred, average='binary', pos_label=1))
print(f1_score(true, pred, average='binary', pos_label=0))
print(f1_score(true, pred, average='micro'))
print(f1_score(true, pred, average='macro'))

0.8
0.4
0.7
0.6000000000000001


In [244]:
import random

true = [0] * 4000 + [1] * 6000
pred = [0] * 1000 + [1] * 9000

random.shuffle(true)
random.shuffle(pred)

print(f1_score(true, pred, average='binary', pos_label=1))
print(f1_score(true, pred, average='binary', pos_label=0))
print(f1_score(true, pred, average='micro'))
print(f1_score(true, pred, average='macro'))

0.7197333333333333
0.1592
0.5796
0.43946666666666667
